Repository lhmouse/asteria, pull requests merged in 2018-10, with the labels that each got.

#23 Rewrite Makefile rules for PCH.
  Makefile.am
Labels: category:problem-minor, status:in-progress

#24 Optimize function calls by using bundled pre-defined references.
  asteria/src/abstract_context.cpp
  asteria/src/abstract_context.hpp
  asteria/src/analytic_context.cpp
  asteria/src/analytic_context.hpp
  asteria/src/executive_context.cpp
  asteria/src/executive_context.hpp
  asteria/src/statement.cpp
  asteria/src/xpnode.cpp
  test/expression.cpp
  test/simple_source_file.cpp
Labels: category:optimization, status:in-progress

#30 auto -> Size
  asteria/src/variable_hashset.cpp
Labels: category:problem-minor, status:resolved-fixed
